apiVersion: 1

datasources:
  # Victoria Metrics (Local)
  - name: LiteLLM Metrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
    editable: true
