{
 "title": "Infrastructure",
 "tags": [
  "infrastructure",
  "ecs",
  "cloudfront",
  "alb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cw_datasource", "label": "CloudWatch", "query": "cloudwatch" },
   { "name": "cluster", "label": "ECS Cluster", "query": "kong-llm-gateway-poc" },
   {
    "name": "alb",
    "label": "ALB",
    "query": "app/kong-llm-gateway-poc/51c71d742f86df34"
   },
   { "name": "cf_distribution", "label": "CloudFront Distribution", "query": "E2YLG986169JZU" }
  ]
 },
 "panels": [
  { "title": "ECS Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kong Running Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "kong" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Grafana Running Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "grafana" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Kong CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "kong" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Kong Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "kong" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Grafana CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "grafana" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Grafana Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "grafana" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "ECS Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "kong" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "grafana" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "kong" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "${cluster}", "ServiceName": "grafana" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "ALB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "ALB Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "${alb}" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ALB Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "${alb}" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "CloudFront Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CloudFront Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DistributionId": "${cf_distribution}", "Region": "Global" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudFront Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DistributionId": "${cf_distribution}", "Region": "Global" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "dimensions": { "DistributionId": "${cf_distribution}", "Region": "Global" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  }
 ]
}