# ArgoCD Application - Kong LLM Gateway (Production)
#
# This manifest deploys Kong Gateway to the prod EKS cluster using ArgoCD.
#
# Prerequisites:
# 1. ArgoCD installed in the cluster
# 2. Git repository registered in ArgoCD
# 3. EKS cluster registered as a destination
#
# IMPORTANT: Production deployments require manual sync (automated sync disabled)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-llm-gateway-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: kong-llm-gateway
    app.kubernetes.io/instance: prod
    app.kubernetes.io/component: api-gateway
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production  # Use a separate project with RBAC for prod

  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: "2.33.0"
    helm:
      releaseName: kong
      valueFiles:
        - https://raw.githubusercontent.com/lorenzogirardi/gw_llm/main/infra/helm/kong/values-base.yaml
        - https://raw.githubusercontent.com/lorenzogirardi/gw_llm/main/infra/helm/kong/values-prod.yaml
      # Override service account annotation with IRSA role
      parameters:
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "${KONG_ROLE_ARN}"  # Replace with actual ARN from Terraform output

  destination:
    server: ${PROD_CLUSTER_URL}  # Replace with production cluster URL
    namespace: kong

  # Manual sync for production - requires approval
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  # Rollback configuration
  revisionHistoryLimit: 10

  # Health checks
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas

---
# ConfigMaps for Kong declarative config and plugins (Production)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-config-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: kong-config
    app.kubernetes.io/instance: prod
    environment: prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Sync before main app
spec:
  project: production

  source:
    repoURL: https://github.com/lorenzogirardi/gw_llm.git
    targetRevision: main  # Consider using tags for production
    path: infra/k8s/kong-config
    directory:
      recurse: false

  destination:
    server: ${PROD_CLUSTER_URL}
    namespace: kong

  # Manual sync for production configs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---
# ArgoCD Project for Production (with RBAC restrictions)

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
spec:
  description: Production environment applications

  # Only allow specific sources
  sourceRepos:
    - https://github.com/lorenzogirardi/gw_llm.git
    - https://charts.konghq.com

  # Only allow specific destinations
  destinations:
    - namespace: kong
      server: ${PROD_CLUSTER_URL}
    - namespace: monitoring
      server: ${PROD_CLUSTER_URL}

  # Deny all cluster-scoped resources by default
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: networking.k8s.io
      kind: IngressClass

  # Allow specific namespace-scoped resources
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: Ingress
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget

  # Require manual sync for production
  syncWindows:
    - kind: allow
      schedule: "0 9-17 * * 1-5"  # Allow syncs Mon-Fri 9am-5pm
      duration: 8h
      applications:
        - "*"
      manualSync: true

  # Orphaned resources monitoring
  orphanedResources:
    warn: true
