# ArgoCD Application - Kong LLM Gateway (Development)
#
# This manifest deploys Kong Gateway to the dev EKS cluster using ArgoCD.
#
# Prerequisites:
# 1. ArgoCD installed in the cluster
# 2. Git repository registered in ArgoCD
# 3. EKS cluster registered as a destination

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-llm-gateway-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: kong-llm-gateway
    app.kubernetes.io/instance: dev
    app.kubernetes.io/component: api-gateway
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: "2.33.0"
    helm:
      releaseName: kong
      valueFiles:
        - https://raw.githubusercontent.com/lorenzogirardi/gw_llm/main/infra/helm/kong/values-base.yaml
        - https://raw.githubusercontent.com/lorenzogirardi/gw_llm/main/infra/helm/kong/values-dev.yaml
      # Override service account annotation with IRSA role
      parameters:
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "${KONG_ROLE_ARN}"  # Replace with actual ARN from Terraform output

  destination:
    server: https://kubernetes.default.svc  # Or use external cluster URL
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs

  # Notifications (optional)
  # Requires argocd-notifications to be installed
  # annotations:
  #   notifications.argoproj.io/subscribe.on-sync-succeeded.slack: kong-deployments
  #   notifications.argoproj.io/subscribe.on-sync-failed.slack: kong-deployments

---
# ConfigMaps for Kong declarative config and plugins
# These are managed separately and synced before the main application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-config-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: kong-config
    app.kubernetes.io/instance: dev
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Sync before main app
spec:
  project: default

  source:
    repoURL: https://github.com/lorenzogirardi/gw_llm.git
    targetRevision: main
    path: infra/k8s/kong-config
    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
